import 'dart:math';
import 'package:flutter/foundation.dart';

import '../data/progress_store.dart';
import '../feedback/haptics.dart';

/// Pipe-rotation puzzle engine — the game's second, mechanically distinct mode.
///
/// The board is an N×N grid of pipe tiles. Each tile exposes a set of open
/// sides encoded as a 4-bit mask (bit0=N, bit1=E, bit2=S, bit3=W). Tapping a
/// tile rotates it 90° clockwise. Lava flows from the source tile through any
/// chain of tiles whose touching sides are both open; the level is solved when
/// that flow reaches the drain tile.
///
/// Puzzles are generated by carving a guaranteed path from source to drain,
/// filling the rest with random pipes, then randomly rotating every tile — so
/// a solution always exists.
class FlowEngine extends ChangeNotifier {
  FlowEngine({Random? rng}) : _rng = rng ?? Random();

  final Random _rng;

  static const _dr = [-1, 0, 1, 0]; // N, E, S, W
  static const _dc = [0, 1, 0, -1];

  int _level = 0;
  int _size = 3;
  List<int> _masks = const [];
  int _src = 0;
  int _dst = 0;
  int _moves = 0;
  bool _solved = false;
  Set<int> _lit = <int>{};

  int get level => _level;
  int get size => _size;
  int get moves => _moves;
  bool get solved => _solved;
  int get sourceIndex => _src;
  int get drainIndex => _dst;
  int bestMoves(int level) => ProgressStore.flowBestMoves(level);

  int maskAt(int r, int c) => _masks[r * _size + c];
  bool isLit(int r, int c) => _lit.contains(r * _size + c);
  bool isSource(int r, int c) => r * _size + c == _src;
  bool isDrain(int r, int c) => r * _size + c == _dst;

  /// Board size grows gently with level, capped at 6×6.
  static int sizeForLevel(int level) => (3 + level ~/ 2).clamp(3, 6);

  void load(int level) {
    _level = level;
    _size = sizeForLevel(level);
    _moves = 0;
    _solved = false;
    _generate();
    _recompute();
    notifyListeners();
  }

  void reset() => load(_level);

  void rotate(int r, int c) {
    if (_solved) return;
    final i = r * _size + c;
    _masks[i] = _rotateCW(_masks[i]);
    _moves++;
    Feedback.good();
    _recompute();
    if (_solved) {
      Feedback.milestone();
      ProgressStore.setFlowBestMoves(_level, _moves);
      ProgressStore.setFlowLevel(_level + 1);
    }
    notifyListeners();
  }

  int _rotateCW(int m) {
    var r = 0;
    for (var d = 0; d < 4; d++) {
      if ((m >> d) & 1 == 1) r |= 1 << ((d + 1) % 4);
    }
    return r;
  }

  void _recompute() {
    _lit = _flood();
    _solved = _lit.contains(_dst);
  }

  Set<int> _flood() {
    final lit = <int>{};
    final stack = <int>[_src];
    while (stack.isNotEmpty) {
      final idx = stack.removeLast();
      if (lit.contains(idx)) continue;
      lit.add(idx);
      final r = idx ~/ _size, c = idx % _size, m = _masks[idx];
      for (var d = 0; d < 4; d++) {
        if ((m >> d) & 1 == 0) continue;
        final nr = r + _dr[d], nc = c + _dc[d];
        if (nr < 0 || nc < 0 || nr >= _size || nc >= _size) continue;
        final n = nr * _size + nc;
        if ((_masks[n] >> ((d + 2) % 4)) & 1 == 1) stack.add(n);
      }
    }
    return lit;
  }

  // ── Generation ──────────────────────────────────────────────────────
  void _generate() {
    final n = _size;
    _masks = List<int>.filled(n * n, 0);
    _src = _rng.nextInt(n); // somewhere on the top row
    _dst = (n - 1) * n + _rng.nextInt(n); // somewhere on the bottom row

    final path = _carvePath();
    for (var k = 0; k < path.length - 1; k++) {
      final a = path[k], b = path[k + 1];
      final d = _dirBetween(a, b);
      _masks[a] |= 1 << d;
      _masks[b] |= 1 << ((d + 2) % 4);
    }

    // Fill the remaining tiles with random 2–3 way pipes for visual density.
    const shapes = [0x5, 0xA, 0x3, 0x6, 0xC, 0x9, 0x7, 0xB, 0xD, 0xE];
    for (var i = 0; i < _masks.length; i++) {
      if (_masks[i] == 0) _masks[i] = shapes[_rng.nextInt(shapes.length)];
    }

    // Scramble every tile so the player has to rebuild the route.
    for (var i = 0; i < _masks.length; i++) {
      final turns = _rng.nextInt(4);
      for (var t = 0; t < turns; t++) {
        _masks[i] = _rotateCW(_masks[i]);
      }
    }
  }

  int _dirBetween(int a, int b) {
    final ar = a ~/ _size, ac = a % _size, br = b ~/ _size, bc = b % _size;
    if (br == ar - 1) return 0; // N
    if (bc == ac + 1) return 1; // E
    if (br == ar + 1) return 2; // S
    return 3; // W
  }

  /// Randomised DFS that always finds a route from source to drain.
  List<int> _carvePath() {
    final n = _size;
    final visited = List<bool>.filled(n * n, false);
    final path = <int>[];

    bool dfs(int idx) {
      visited[idx] = true;
      path.add(idx);
      if (idx == _dst) return true;
      final r = idx ~/ n, c = idx % n;
      final order = [0, 1, 2, 3]..shuffle(_rng);
      for (final d in order) {
        final nr = r + _dr[d], nc = c + _dc[d];
        if (nr < 0 || nc < 0 || nr >= n || nc >= n) continue;
        final ni = nr * n + nc;
        if (visited[ni]) continue;
        if (dfs(ni)) return true;
      }
      path.removeLast();
      return false;
    }

    dfs(_src);
    if (path.isEmpty || path.last != _dst) {
      // Fallback: straight L-route guaranteed to connect.
      return _fallbackPath();
    }
    return path;
  }

  List<int> _fallbackPath() {
    final n = _size;
    final p = <int>[];
    final sc = _src % n;
    for (var r = 0; r < n; r++) {
      p.add(r * n + sc);
    }
    final dc = _dst % n;
    final lo = min(sc, dc), hi = max(sc, dc);
    for (var c = lo; c <= hi; c++) {
      final idx = (n - 1) * n + c;
      if (!p.contains(idx)) p.add(idx);
    }
    return p;
  }
}
